export const PUZZLE_WORDS = [
  // easy — 3 letters
  {
    id: "w1",
    word: "CAT",
    hint: "Furry pet that says 'meow'",
    category: "Animals",
  },
  {
    id: "w2",
    word: "SUN",
    hint: "Bright star that lights up the day",
    category: "Nature",
  },
  {
    id: "w3",
    word: "CUP",
    hint: "Container you drink coffee or tea from",
    category: "Objects",
  },
  {
    id: "w4",
    word: "DOG",
    hint: "Barking pet, often called man's best friend",
    category: "Animals",
  },
  {
    id: "w5",
    word: "HAT",
    hint: "Clothing item worn on your head",
    category: "Clothing",
  },
  {
    id: "w6",
    word: "BED",
    hint: "Furniture you sleep on at night",
    category: "Furniture",
  },
  {
    id: "w7",
    word: "CAR",
    hint: "Four-wheeled vehicle used for driving",
    category: "Transport",
  },
  {
    id: "w8",
    word: "KEY",
    hint: "Metal object that opens a door or lock",
    category: "Objects",
  },
  {
    id: "w9",
    word: "BAG",
    hint: "Item used to carry your belongings",
    category: "Objects",
  },
  {
    id: "w10",
    word: "BOX",
    hint: "Cardboard or wooden container for storing things",
    category: "Objects",
  },
  {
    id: "w11",
    word: "EYE",
    hint: "Body part you use to see",
    category: "Body",
  },
  {
    id: "w12",
    word: "RUN",
    hint: "Move quickly using your legs",
    category: "Action",
  },
  {
    id: "w13",
    word: "FLY",
    hint: "Move through the air like a bird",
    category: "Action",
  },
  {
    id: "w14",
    word: "ICE",
    hint: "Frozen water, often used to cool drinks",
    category: "Nature",
  },
  {
    id: "w15",
    word: "PIE",
    hint: "Sweet baked dessert with a crust",
    category: "Food",
  },
  {
    id: "w16",
    word: "TEA",
    hint: "Hot beverage made from leaves",
    category: "Food",
  },
  {
    id: "w17",
    word: "PEN",
    hint: "Tool used for writing with ink",
    category: "Objects",
  },
  {
    id: "w18",
    word: "BUS",
    hint: "Large public vehicle that carries many passengers",
    category: "Transport",
  },
  {
    id: "w19",
    word: "BAT",
    hint: "Wooden stick used to hit a baseball",
    category: "Objects",
  },
  {
    id: "w20",
    word: "BEE",
    hint: "Stinging insect that makes honey",
    category: "Animals",
  },
  {
    id: "w21",
    word: "OWL",
    hint: "Nocturnal bird known for hooting",
    category: "Animals",
  },
  {
    id: "w22",
    word: "EAR",
    hint: "Body part you use to hear sounds",
    category: "Body",
  },
  {
    id: "w23",
    word: "ARM",
    hint: "Upper limb of the body with a hand",
    category: "Body",
  },
  {
    id: "w24",
    word: "LEG",
    hint: "Lower limb used for walking",
    category: "Body",
  },
  {
    id: "w25",
    word: "JAM",
    hint: "Sweet fruit spread eaten on toast",
    category: "Food",
  },
  {
    id: "w26",
    word: "NET",
    hint: "Mesh tool used to catch fish or balls",
    category: "Objects",
  },
  {
    id: "w27",
    word: "PIG",
    hint: "Pink farm animal that says 'oink'",
    category: "Animals",
  },
  {
    id: "w28",
    word: "COW",
    hint: "Farm animal that gives milk",
    category: "Animals",
  },
  {
    id: "w29",
    word: "FOX",
    hint: "Clever wild animal with a bushy tail",
    category: "Animals",
  },
  {
    id: "w30",
    word: "OAK",
    hint: "Tall, strong tree that produces acorns",
    category: "Nature",
  },
  {
    id: "w31",
    word: "AIR",
    hint: "Invisible gas we breathe to stay alive",
    category: "Nature",
  },
  {
    id: "w32",
    word: "ART",
    hint: "Creative paintings, drawings, or sculptures",
    category: "Art",
  },
  {
    id: "w33",
    word: "ACE",
    hint: "Highest ranking card in a deck",
    category: "Games",
  },
  {
    id: "w34",
    word: "AGE",
    hint: "Number of years a person has lived",
    category: "Time",
  },
  {
    id: "w35",
    word: "APE",
    hint: "Large primate similar to a gorilla",
    category: "Animals",
  },
  {
    id: "w36",
    word: "AXE",
    hint: "Tool with a sharp blade for chopping wood",
    category: "Tools",
  },
  {
    id: "w37",
    word: "ATE",
    hint: "Past tense of the word 'eat'",
    category: "Action",
  },
  {
    id: "w38",
    word: "BIT",
    hint: "A very small piece or amount",
    category: "Objects",
  },
  {
    id: "w39",
    word: "BOW",
    hint: "Decorative knot made with ribbon",
    category: "Objects",
  },
  { id: "w40", word: "BOY", hint: "Young male child", category: "People" },
  {
    id: "w41",
    word: "BUG",
    hint: "Small crawling insect",
    category: "Animals",
  },
  {
    id: "w42",
    word: "BUT",
    hint: "Conjunction meaning 'however'",
    category: "Words",
  },
  {
    id: "w43",
    word: "BUY",
    hint: "To purchase something with money",
    category: "Action",
  },
  {
    id: "w44",
    word: "COD",
    hint: "Popular white fish often eaten fried",
    category: "Animals",
  },
  {
    id: "w45",
    word: "COT",
    hint: "Small portable bed for babies",
    category: "Furniture",
  },
  {
    id: "w46",
    word: "CRY",
    hint: "Shed tears when sad or hurt",
    category: "Action",
  },
  {
    id: "w47",
    word: "CUT",
    hint: "Use scissors or a knife to slice",
    category: "Action",
  },
  {
    id: "w48",
    word: "DIG",
    hint: "Use a shovel to make a hole in the ground",
    category: "Action",
  },
  { id: "w49", word: "DRY", hint: "Not wet or damp", category: "Adjective" },
  {
    id: "w50",
    word: "DYE",
    hint: "Substance used to change color of fabric",
    category: "Action",
  },
  {
    id: "w51",
    word: "EAT",
    hint: "Consume food with your mouth",
    category: "Action",
  },
  {
    id: "w52",
    word: "ELF",
    hint: "Small magical creature with pointed ears",
    category: "Fantasy",
  },
  {
    id: "w53",
    word: "ELM",
    hint: "Tall tree with broad leaves",
    category: "Nature",
  },
  {
    id: "w54",
    word: "END",
    hint: "The final part of something",
    category: "Words",
  },
  {
    id: "w55",
    word: "ERA",
    hint: "A long period of time in history",
    category: "Time",
  },
  {
    id: "w56",
    word: "FAR",
    hint: "A long distance away",
    category: "Distance",
  },
  {
    id: "w57",
    word: "FAT",
    hint: "Having a large amount of body weight",
    category: "Adjective",
  },
  {
    id: "w58",
    word: "FEW",
    hint: "A small number of things",
    category: "Quantity",
  },
  {
    id: "w59",
    word: "FIG",
    hint: "Sweet purple or green fruit with seeds",
    category: "Food",
  },
  {
    id: "w60",
    word: "FIN",
    hint: "Part of a fish used for swimming",
    category: "Animals",
  },
  {
    id: "w61",
    word: "FIT",
    hint: "In good physical shape and healthy",
    category: "Adjective",
  },
  {
    id: "w62",
    word: "FUR",
    hint: "Soft hair covering many animals",
    category: "Animals",
  },
  {
    id: "w63",
    word: "GAP",
    hint: "An empty space or opening",
    category: "Objects",
  },
  {
    id: "w64",
    word: "GAS",
    hint: "Fuel used to power cars",
    category: "Objects",
  },
  {
    id: "w65",
    word: "GEL",
    hint: "Thick, jelly-like substance",
    category: "Objects",
  },

  // medium — 5 letters
  {
    id: "w66",
    word: "APPLE",
    hint: "Red or green fruit that keeps the doctor away",
    category: "Food",
  },
  {
    id: "w67",
    word: "CLOCK",
    hint: "Device that shows what time it is",
    category: "Objects",
  },
  {
    id: "w68",
    word: "CHAIR",
    hint: "Furniture designed for sitting",
    category: "Furniture",
  },
  {
    id: "w69",
    word: "MUSIC",
    hint: "Sounds arranged in a pleasing way",
    category: "Art",
  },
  {
    id: "w70",
    word: "PLANT",
    hint: "Green living thing that grows in soil",
    category: "Nature",
  },
  {
    id: "w71",
    word: "BREAD",
    hint: "Food made from flour and baked in an oven",
    category: "Food",
  },
  {
    id: "w72",
    word: "SMILE",
    hint: "Happy facial expression showing teeth",
    category: "Emotion",
  },
  {
    id: "w73",
    word: "DREAM",
    hint: "Story your mind creates while you sleep",
    category: "Sleep",
  },
  {
    id: "w74",
    word: "HEART",
    hint: "Organ in your chest that pumps blood",
    category: "Body",
  },
  {
    id: "w75",
    word: "BEACH",
    hint: "Sandy area next to the sea or ocean",
    category: "Nature",
  },
  {
    id: "w76",
    word: "TABLE",
    hint: "Furniture with a flat top for eating or working",
    category: "Furniture",
  },
  {
    id: "w77",
    word: "WATER",
    hint: "Clear liquid essential for all life",
    category: "Nature",
  },
  {
    id: "w78",
    word: "LIGHT",
    hint: "Brightness that allows us to see",
    category: "Physics",
  },
  {
    id: "w79",
    word: "SLEEP",
    hint: "Rest your body and mind at night",
    category: "Action",
  },
  {
    id: "w80",
    word: "PEACE",
    hint: "State of calm with no fighting",
    category: "Emotion",
  },
  {
    id: "w81",
    word: "HOUSE",
    hint: "Building where people live",
    category: "Places",
  },
  {
    id: "w82",
    word: "PHONE",
    hint: "Device used to call and text people",
    category: "Technology",
  },
  {
    id: "w83",
    word: "DANCE",
    hint: "Move your body to the rhythm of music",
    category: "Action",
  },
  {
    id: "w84",
    word: "HAPPY",
    hint: "Feeling full of joy and cheer",
    category: "Emotion",
  },
  {
    id: "w85",
    word: "ANGRY",
    hint: "Feeling very mad or upset",
    category: "Emotion",
  },
  {
    id: "w86",
    word: "TIRED",
    hint: "Feeling like you need to rest or sleep",
    category: "Emotion",
  },
  {
    id: "w87",
    word: "QUIET",
    hint: "Making little or no noise",
    category: "Adjective",
  },
  {
    id: "w88",
    word: "BRAVE",
    hint: "Showing courage and no fear",
    category: "Adjective",
  },
  {
    id: "w89",
    word: "CLEAN",
    hint: "Free from dirt or mess",
    category: "Adjective",
  },
  {
    id: "w90",
    word: "DIRTY",
    hint: "Covered with dirt or stains",
    category: "Adjective",
  },
  {
    id: "w91",
    word: "SWEET",
    hint: "Taste like sugar or candy",
    category: "Taste",
  },
  {
    id: "w92",
    word: "SOUR",
    hint: "Sharp acidic taste like lemon",
    category: "Taste",
  },
  {
    id: "w93",
    word: "ROUND",
    hint: "Shape like a circle or ball",
    category: "Shape",
  },
  {
    id: "w94",
    word: "SHARP",
    hint: "Able to cut or pierce easily",
    category: "Adjective",
  },
  {
    id: "w95",
    word: "DULL",
    hint: "Not sharp or exciting",
    category: "Adjective",
  },
  {
    id: "w96",
    word: "QUICK",
    hint: "Moving or happening very fast",
    category: "Speed",
  },
  { id: "w97", word: "SLOW", hint: "Moving at a low speed", category: "Speed" },
  {
    id: "w98",
    word: "YOUNG",
    hint: "Not old, in early stage of life",
    category: "Age",
  },
  {
    id: "w99",
    word: "OLD",
    hint: "Having lived for many years",
    category: "Age",
  },
  { id: "w100", word: "SMALL", hint: "Little in size", category: "Size" },
  { id: "w101", word: "LARGE", hint: "Big in size", category: "Size" },
  { id: "w102", word: "HEAVY", hint: "Weighing a lot", category: "Weight" },
  { id: "w103", word: "LIGHT", hint: "Not weighing much", category: "Weight" },
  {
    id: "w104",
    word: "THICK",
    hint: "Wide and not thin",
    category: "Thickness",
  },
  {
    id: "w105",
    word: "THIN",
    hint: "Narrow and not thick",
    category: "Thickness",
  },
  {
    id: "w106",
    word: "COLD",
    hint: "Low in temperature, like ice",
    category: "Temperature",
  },
  {
    id: "w107",
    word: "WARM",
    hint: "Pleasantly high in temperature",
    category: "Temperature",
  },
  {
    id: "w108",
    word: "TOUCH",
    hint: "Feel something with your hands",
    category: "Action",
  },
  {
    id: "w109",
    word: "SIGHT",
    hint: "The sense of seeing",
    category: "Senses",
  },
  {
    id: "w110",
    word: "SMELL",
    hint: "The sense of detecting odors",
    category: "Senses",
  },
  {
    id: "w111",
    word: "TASTE",
    hint: "The sense of flavor in your mouth",
    category: "Senses",
  },
  {
    id: "w112",
    word: "SOUND",
    hint: "What your ears detect",
    category: "Senses",
  },
  {
    id: "w113",
    word: "COLOR",
    hint: "Red, blue, green, yellow etc.",
    category: "Visual",
  },
  {
    id: "w114",
    word: "SHAPE",
    hint: "Form such as circle, square, or triangle",
    category: "Visual",
  },
  { id: "w115", word: "STONE", hint: "Hard piece of rock", category: "Nature" },
  {
    id: "w116",
    word: "GRASS",
    hint: "Green plants covering lawns and fields",
    category: "Nature",
  },
  {
    id: "w117",
    word: "CLOUD",
    hint: "White or grey fluffy mass in the sky",
    category: "Nature",
  },
  {
    id: "w118",
    word: "STORM",
    hint: "Bad weather with strong wind and rain",
    category: "Nature",
  },
  {
    id: "w119",
    word: "RIVER",
    hint: "Long flowing body of water",
    category: "Nature",
  },
  {
    id: "w120",
    word: "OCEAN",
    hint: "Huge body of salt water covering most of Earth",
    category: "Nature",
  },

  // hard — 8+ letters
  {
    id: "w121",
    word: "CALENDAR",
    hint: "Chart that shows days, weeks, and months",
    category: "Objects",
  },
  {
    id: "w122",
    word: "UMBRELLA",
    hint: "Object you open to stay dry in the rain",
    category: "Objects",
  },
  {
    id: "w123",
    word: "ELEPHANT",
    hint: "Largest land animal with a long trunk",
    category: "Animals",
  },
  {
    id: "w124",
    word: "COMPUTER",
    hint: "Electronic device used for work and internet",
    category: "Technology",
  },
  {
    id: "w125",
    word: "MOUNTAIN",
    hint: "Very tall natural land formation",
    category: "Nature",
  },
  {
    id: "w126",
    word: "SANDWICH",
    hint: "Food made with two slices of bread",
    category: "Food",
  },
  {
    id: "w127",
    word: "HOSPITAL",
    hint: "Place where sick or injured people get treatment",
    category: "Places",
  },
  {
    id: "w128",
    word: "DOCUMENT",
    hint: "Official written paper or file",
    category: "Objects",
  },
  {
    id: "w129",
    word: "KEYBOARD",
    hint: "Device with keys for typing on a computer",
    category: "Technology",
  },
  {
    id: "w130",
    word: "CHILDREN",
    hint: "Young human beings (plural of child)",
    category: "People",
  },
  {
    id: "w131",
    word: "DARKNESS",
    hint: "Complete absence of light",
    category: "Physics",
  },
  {
    id: "w132",
    word: "BIRTHDAY",
    hint: "The anniversary of the day you were born",
    category: "Events",
  },
  {
    id: "w133",
    word: "LAUGHTER",
    hint: "Sound people make when they find something funny",
    category: "Emotion",
  },
  {
    id: "w134",
    word: "TREASURE",
    hint: "Valuable gold, jewels, or riches",
    category: "Objects",
  },
  {
    id: "w135",
    word: "LANGUAGE",
    hint: "System of words used for communication",
    category: "Learning",
  },
  {
    id: "w136",
    word: "PAINTING",
    hint: "Artwork created with colors on canvas",
    category: "Art",
  },
  {
    id: "w137",
    word: "MEDICINE",
    hint: "Substance used to treat or cure illness",
    category: "Health",
  },
  {
    id: "w138",
    word: "SWIMMING",
    hint: "Moving through water using your arms and legs",
    category: "Action",
  },
  {
    id: "w139",
    word: "BUILDING",
    hint: "Large structure with walls and a roof",
    category: "Places",
  },
  {
    id: "w140",
    word: "LEARNING",
    hint: "The process of gaining knowledge",
    category: "Education",
  },
  {
    id: "w141",
    word: "BUTTERFLY",
    hint: "Colorful insect with large wings",
    category: "Animals",
  },
  {
    id: "w142",
    word: "WONDERFUL",
    hint: "Extremely good or amazing",
    category: "Adjective",
  },
  {
    id: "w143",
    word: "KNOWLEDGE",
    hint: "Facts, information, and skills learned",
    category: "Education",
  },
  {
    id: "w144",
    word: "BREAKFAST",
    hint: "First meal of the day, usually in the morning",
    category: "Food",
  },
  {
    id: "w145",
    word: "BEAUTIFUL",
    hint: "Very pleasing to look at",
    category: "Adjective",
  },
  {
    id: "w146",
    word: "ADVENTURE",
    hint: "Exciting and often risky experience",
    category: "Events",
  },
  {
    id: "w147",
    word: "DINOSAUR",
    hint: "Huge extinct reptile from millions of years ago",
    category: "Animals",
  },
  {
    id: "w148",
    word: "BIRTHDAY",
    hint: "Special annual celebration of your birth",
    category: "Events",
  },
  {
    id: "w149",
    word: "DIFFERENT",
    hint: "Not the same as something else",
    category: "Adjective",
  },
  {
    id: "w150",
    word: "DIFFICULT",
    hint: "Hard to do or understand",
    category: "Adjective",
  },
  {
    id: "w151",
    word: "FRIENDSHIP",
    hint: "Close and trusting relationship between friends",
    category: "People",
  },
  {
    id: "w152",
    word: "IMPORTANT",
    hint: "Of great significance or value",
    category: "Adjective",
  },
  {
    id: "w153",
    word: "FURNITURE",
    hint: "Tables, chairs, beds, and sofas in a house",
    category: "Objects",
  },
  {
    id: "w154",
    word: "GRATEFUL",
    hint: "Feeling thankful and appreciative",
    category: "Emotion",
  },
  {
    id: "w155",
    word: "GRATEFUL",
    hint: "Feeling full of thanks",
    category: "Emotion",
  },
  {
    id: "w156",
    word: "HAPPINESS",
    hint: "The state of being very joyful",
    category: "Emotion",
  },
  {
    id: "w157",
    word: "HERITAGE",
    hint: "Traditions and culture passed down from ancestors",
    category: "Culture",
  },
  {
    id: "w158",
    word: "HISTORIC",
    hint: "Important and famous from the past",
    category: "History",
  },
  {
    id: "w159",
    word: "HOLIDAY",
    hint: "Special day when people don't work or go to school",
    category: "Events",
  },
  {
    id: "w160",
    word: "HOMEWORK",
    hint: "School assignments done at home",
    category: "Education",
  },
  {
    id: "w161",
    word: "HUMANITY",
    hint: "All human beings together",
    category: "People",
  },
  { id: "w162", word: "HUSBAND", hint: "A married man", category: "People" },
  {
    id: "w163",
    word: "IDENTITY",
    hint: "Who a person is, their name and characteristics",
    category: "People",
  },
  {
    id: "w164",
    word: "INCREASE",
    hint: "To make something bigger or greater",
    category: "Action",
  },
  {
    id: "w165",
    word: "INDUSTRY",
    hint: "Large-scale manufacturing or business sector",
    category: "Work",
  },
  {
    id: "w166",
    word: "INSTANCE",
    hint: "A specific example of something",
    category: "Words",
  },
  {
    id: "w167",
    word: "INTERIOR",
    hint: "The inside part of a building or room",
    category: "Places",
  },
  {
    id: "w168",
    word: "INTERNET",
    hint: "Global network connecting computers worldwide",
    category: "Technology",
  },
  {
    id: "w169",
    word: "INTERVAL",
    hint: "The time or space between two things",
    category: "Time",
  },
  {
    id: "w170",
    word: "INVADING",
    hint: "Entering a place by force",
    category: "Action",
  },
  {
    id: "w171",
    word: "INVOLVED",
    hint: "Taking part or participating in something",
    category: "Action",
  },
  {
    id: "w172",
    word: "ISOLATED",
    hint: "Separated and alone from others",
    category: "Adjective",
  },
  {
    id: "w173",
    word: "JUDGMENT",
    hint: "The ability to make decisions or form opinions",
    category: "Action",
  },
  {
    id: "w174",
    word: "KINDNESS",
    hint: "The quality of being nice and considerate",
    category: "Emotion",
  },
  {
    id: "w175",
    word: "LOCATION",
    hint: "A particular place or position",
    category: "Places",
  },
  {
    id: "w176",
    word: "MAJORITY",
    hint: "The greater part or number of something",
    category: "Quantity",
  },
  {
    id: "w177",
    word: "MATERIAL",
    hint: "Substance from which things are made",
    category: "Objects",
  },
  {
    id: "w178",
    word: "MINORITY",
    hint: "The smaller part of a group",
    category: "Quantity",
  },
  {
    id: "w179",
    word: "MODERATE",
    hint: "Neither small nor large, medium level",
    category: "Quantity",
  },
  {
    id: "w180",
    word: "MONUMENT",
    hint: "Large structure built to remember something",
    category: "Places",
  },
  {
    id: "w181",
    word: "MORTGAGE",
    hint: "Loan taken to buy a house",
    category: "Finance",
  },
  {
    id: "w182",
    word: "MULTIPLY",
    hint: "Mathematical operation to increase numbers",
    category: "Action",
  },
  {
    id: "w183",
    word: "MUSICIAN",
    hint: "Person who plays or creates music",
    category: "Art",
  },
  {
    id: "w184",
    word: "NATIONAL",
    hint: "Relating to an entire country",
    category: "Places",
  },
  {
    id: "w185",
    word: "NEGATIVE",
    hint: "Bad, harmful, or the opposite of positive",
    category: "Adjective",
  },
  {
    id: "w186",
    word: "NEIGHBOR",
    hint: "Person who lives near you",
    category: "People",
  },
  {
    id: "w187",
    word: "NEWSPAPER",
    hint: "Printed paper with daily news",
    category: "Media",
  },
  {
    id: "w188",
    word: "NOTEBOOK",
    hint: "Book used for writing notes",
    category: "Objects",
  },
  {
    id: "w189",
    word: "NUMEROUS",
    hint: "A very large number of things",
    category: "Quantity",
  },
  {
    id: "w190",
    word: "OBSERVER",
    hint: "Someone who watches something carefully",
    category: "People",
  },
  {
    id: "w191",
    word: "OBSTACLE",
    hint: "Something that blocks your way",
    category: "Objects",
  },
  {
    id: "w192",
    word: "OCCASION",
    hint: "A special event or celebration",
    category: "Events",
  },
  {
    id: "w193",
    word: "OPPOSITE",
    hint: "Completely different or reverse",
    category: "Adjective",
  },
  {
    id: "w194",
    word: "OPTIONAL",
    hint: "Something you can choose but not required",
    category: "Adjective",
  },
  {
    id: "w195",
    word: "ORIGINAL",
    hint: "First or completely new, not copied",
    category: "Adjective",
  },
  {
    id: "w196",
    word: "ORGANISM",
    hint: "Any living plant or animal",
    category: "Science",
  },
  {
    id: "w197",
    word: "OVERCOME",
    hint: "Successfully deal with or defeat a problem",
    category: "Action",
  },
  {
    id: "w198",
    word: "OVERHEAD",
    hint: "Positioned above your head",
    category: "Direction",
  },
  {
    id: "w199",
    word: "OVERLOOK",
    hint: "Fail to notice or deliberately ignore",
    category: "Action",
  },
  {
    id: "w200",
    word: "OVERVIEW",
    hint: "A general summary or broad look at something",
    category: "Words",
  },
];
