export const RECALL_OBJECTS = [
  { id: "o1", emoji: "🔑", label: "Keys", category: "Household" },
  { id: "o2", emoji: "👓", label: "Glasses", category: "Personal" },
  { id: "o3", emoji: "☕", label: "Cup", category: "Household" },
  { id: "o4", emoji: "📱", label: "Phone", category: "Technology" },
  { id: "o5", emoji: "🖊️", label: "Pen", category: "Stationery" },
  { id: "o6", emoji: "🧦", label: "Socks", category: "Clothing" },
  { id: "o7", emoji: "🪴", label: "Plant", category: "Nature" },
  { id: "o8", emoji: "🕯️", label: "Candle", category: "Household" },
  { id: "o9", emoji: "📖", label: "Book", category: "Objects" },
  { id: "o10", emoji: "⌚", label: "Watch", category: "Personal" },
  { id: "o11", emoji: "🎧", label: "Headphones", category: "Technology" },
  { id: "o12", emoji: "🧢", label: "Cap", category: "Clothing" },
  { id: "o13", emoji: "💼", label: "Briefcase", category: "Objects" },
  { id: "o14", emoji: "🎒", label: "Backpack", category: "Objects" },
  { id: "o15", emoji: "👜", label: "Purse", category: "Objects" },
  { id: "o16", emoji: "🧤", label: "Gloves", category: "Clothing" },
  { id: "o17", emoji: "🧣", label: "Scarf", category: "Clothing" },
  { id: "o18", emoji: "👞", label: "Shoes", category: "Clothing" },
  { id: "o19", emoji: "🧴", label: "Soap", category: "Hygiene" },
  { id: "o20", emoji: "🪥", label: "Toothbrush", category: "Hygiene" },
  { id: "o21", emoji: "💄", label: "Lipstick", category: "Personal" },
  { id: "o22", emoji: "🧲", label: "Magnet", category: "Objects" },
  { id: "o23", emoji: "🔦", label: "Flashlight", category: "Household" },
  { id: "o24", emoji: "🪒", label: "Razor", category: "Personal" },
  { id: "o25", emoji: "🧼", label: "Sponge", category: "Household" },
  { id: "o26", emoji: "🧹", label: "Broom", category: "Household" },
  { id: "o27", emoji: "🪣", label: "Bucket", category: "Household" },
  { id: "o28", emoji: "🧺", label: "Basket", category: "Household" },
  { id: "o29", emoji: "📺", label: "TV Remote", category: "Technology" },
  { id: "o30", emoji: "💻", label: "Laptop", category: "Technology" },
  { id: "o31", emoji: "⌨️", label: "Keyboard", category: "Technology" },
  { id: "o32", emoji: "🖱️", label: "Mouse", category: "Technology" },
  { id: "o33", emoji: "📷", label: "Camera", category: "Technology" },
  { id: "o34", emoji: "🎮", label: "Game Controller", category: "Technology" },
  { id: "o35", emoji: "💍", label: "Ring", category: "Personal" },
  { id: "o36", emoji: "⛓️", label: "Necklace", category: "Personal" },
  { id: "o37", emoji: "👂", label: "Earrings", category: "Personal" },
  { id: "o38", emoji: "🎓", label: "Hat", category: "Clothing" },
  { id: "o39", emoji: "🧳", label: "Suitcase", category: "Travel" },
  { id: "o40", emoji: "🗺️", label: "Map", category: "Travel" },
  { id: "o41", emoji: "✈️", label: "Airplane Ticket", category: "Travel" },
  { id: "o42", emoji: "🎫", label: "Ticket", category: "Documents" },
  { id: "o43", emoji: "💳", label: "Credit Card", category: "Personal" },
  { id: "o44", emoji: "🪵", label: "Pencil", category: "Stationery" },
  { id: "o45", emoji: "📓", label: "Notebook", category: "Stationery" },
  { id: "o46", emoji: "✂️", label: "Scissors", category: "Stationery" },
  { id: "o47", emoji: "📎", label: "Paper Clip", category: "Stationery" },
  { id: "o48", emoji: "🔐", label: "Lock", category: "Household" },
  { id: "o49", emoji: "🧰", label: "Toolbox", category: "Objects" },
  { id: "o50", emoji: "🎁", label: "Gift Box", category: "Objects" },
];