export const SEQUENCE_ITEMS = [
  { id: "s1", emoji: "🍎", label: "Apple", category: "Food" },
  { id: "s2", emoji: "🐕", label: "Dog", category: "Animal" },
  { id: "s3", emoji: "🚗", label: "Car", category: "Vehicle" },
  { id: "s4", emoji: "🌸", label: "Flower", category: "Nature" },
  { id: "s5", emoji: "📚", label: "Book", category: "Object" },
  { id: "s6", emoji: "🎵", label: "Music", category: "Art" },
  { id: "s7", emoji: "🏠", label: "House", category: "Place" },
  { id: "s8", emoji: "🍊", label: "Orange", category: "Food" },
  { id: "s9", emoji: "🐈", label: "Cat", category: "Animal" },
  { id: "s10", emoji: "✈️", label: "Airplane", category: "Vehicle" },
  { id: "s11", emoji: "🌻", label: "Sunflower", category: "Nature" },
  { id: "s12", emoji: "📓", label: "Notebook", category: "Object" },
  { id: "s13", emoji: "🎸", label: "Guitar", category: "Art" },
  { id: "s14", emoji: "🏖️", label: "Beach", category: "Place" },
  { id: "s15", emoji: "🍕", label: "Pizza", category: "Food" },
  { id: "s16", emoji: "🦁", label: "Lion", category: "Animal" },
  { id: "s17", emoji: "🚂", label: "Train", category: "Vehicle" },
  { id: "s18", emoji: "🌳", label: "Tree", category: "Nature" },
  { id: "s19", emoji: "✏️", label: "Pencil", category: "Object" },
  { id: "s20", emoji: "🎨", label: "Paint Palette", category: "Art" },
  { id: "s21", emoji: "🏰", label: "Castle", category: "Place" },
  { id: "s22", emoji: "🍰", label: "Cake", category: "Food" },
  { id: "s23", emoji: "🦒", label: "Giraffe", category: "Animal" },
  { id: "s24", emoji: "🚁", label: "Helicopter", category: "Vehicle" },
  { id: "s25", emoji: "🌺", label: "Hibiscus", category: "Nature" },
  { id: "s26", emoji: "💻", label: "Computer", category: "Object" },
  { id: "s27", emoji: "🎭", label: "Theater Masks", category: "Art" },
  { id: "s28", emoji: "🗼", label: "Tower", category: "Place" },
  { id: "s29", emoji: "🍇", label: "Grapes", category: "Food" },
  { id: "s30", emoji: "🐘", label: "Elephant", category: "Animal" },
  { id: "s31", emoji: "🚢", label: "Ship", category: "Vehicle" },
  { id: "s32", emoji: "🌙", label: "Moon", category: "Nature" },
  { id: "s33", emoji: "⌚", label: "Watch", category: "Object" },
  { id: "s34", emoji: "🎪", label: "Circus Tent", category: "Art" },
  { id: "s35", emoji: "⛩️", label: "Temple", category: "Place" },
  { id: "s36", emoji: "🥕", label: "Carrot", category: "Food" },
  { id: "s37", emoji: "🐧", label: "Penguin", category: "Animal" },
  { id: "s38", emoji: "🏍️", label: "Motorcycle", category: "Vehicle" },
  { id: "s39", emoji: "⭐", label: "Star", category: "Nature" },
  { id: "s40", emoji: "🎲", label: "Dice", category: "Object" },
  { id: "s41", emoji: "🎬", label: "Movie Clapper", category: "Art" },
  { id: "s42", emoji: "🏛️", label: "Museum", category: "Place" },
  { id: "s43", emoji: "🍓", label: "Strawberry", category: "Food" },
  { id: "s44", emoji: "🦊", label: "Fox", category: "Animal" },
  { id: "s45", emoji: "⛵", label: "Sailboat", category: "Vehicle" },
  { id: "s46", emoji: "❄️", label: "Snowflake", category: "Nature" },
  { id: "s47", emoji: "🎸", label: "Music Note", category: "Object" },
  { id: "s48", emoji: "🖼️", label: "Framed Picture", category: "Art" },
  { id: "s49", emoji: "🏞️", label: "Landscape", category: "Place" },
  { id: "s50", emoji: "🍌", label: "Banana", category: "Food" },
];