const { shuffle, pickDistractors } = require("./gameContentUtils");

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const WEEKDAYS = [
  "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
];

const TIMES_OF_DAY = ["Morning", "Afternoon", "Evening", "Night"];

function getTimeOfDay(hour) {
  if (hour >= 5 && hour < 12) return "Morning";
  if (hour >= 12 && hour < 17) return "Afternoon";
  if (hour >= 17 && hour < 21) return "Evening";
  return "Night";
}

function buildQuestion({ id, question, icon, correctAnswer, pool, optionsCount }) {
  const options = shuffle([
    correctAnswer,
    ...pickDistractors(pool, [correctAnswer], optionsCount - 1),
  ]);
  return { id, question, icon, category: "Time", correctAnswer, options };
}

// Numeric question with plausible near-miss distractors. `pool` may be a fixed
// list of candidate numbers; when omitted we generate neighbours of the answer
// (kept within [min, max]).
function buildNumberQuestion({ id, question, icon, answer, pool, min = 1, max = 999, optionsCount }) {
  let candidates = pool;
  if (!candidates) {
    candidates = [];
    for (let delta = -4; delta <= 4; delta += 1) {
      const value = answer + delta;
      if (delta !== 0 && value >= min && value <= max) candidates.push(value);
    }
  }
  const correctAnswer = String(answer);
  const options = shuffle([
    correctAnswer,
    ...pickDistractors(candidates.map(String), [correctAnswer], optionsCount - 1),
  ]);
  return { id, question, icon, category: "Time", correctAnswer, options };
}

// Deterministic, real-clock orientation questions — never generated by an LLM,
// so "what year/day is it" can never be hallucinated wrong. The pool is larger
// than any single round needs and returned shuffled, so a patient who plays
// repeatedly gets a fresh mix each time instead of the same handful of items.
function buildTimeOrientationQuestions(optionsCount = 3, now = new Date()) {
  const year = now.getFullYear();
  const monthIndex = now.getMonth();
  const month = MONTHS[monthIndex];
  const dayIndex = now.getDay();
  const weekday = WEEKDAYS[dayIndex];
  const dateOfMonth = now.getDate();
  const hour = now.getHours();
  const timeOfDay = getTimeOfDay(hour);
  const yearPool = [year - 2, year - 1, year, year + 1, year + 2].map(String);
  const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();

  const tomorrow = WEEKDAYS[(dayIndex + 1) % 7];
  const yesterday = WEEKDAYS[(dayIndex + 6) % 7];
  const nextMonth = MONTHS[(monthIndex + 1) % 12];
  const isWeekend = dayIndex === 0 || dayIndex === 6;

  const questions = [
    // ── Current date & time awareness (change with the real clock) ──
    buildQuestion({
      id: "ot-year",
      question: "What year is it right now?",
      icon: "\u{1F4C5}",
      correctAnswer: String(year),
      pool: yearPool,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-weekday",
      question: "What day of the week is it today?",
      icon: "\u{1F4C6}",
      correctAnswer: weekday,
      pool: WEEKDAYS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-month",
      question: "What month is it right now?",
      icon: "\u{1F5D3}️",
      correctAnswer: month,
      pool: MONTHS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-timeofday",
      question: "Is it morning, afternoon, evening, or night right now?",
      icon: "⏰",
      correctAnswer: timeOfDay,
      pool: TIMES_OF_DAY,
      optionsCount,
    }),
    buildNumberQuestion({
      id: "ot-dateofmonth",
      question: "What is today's date (the day of the month)?",
      icon: "\u{1F4C5}",
      answer: dateOfMonth,
      min: 1,
      max: 31,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-ampm",
      question: "Right now, is the time AM (before noon) or PM (after noon)?",
      icon: "\u{1F55B}",
      correctAnswer: hour < 12 ? "AM" : "PM",
      pool: ["AM", "PM"],
      optionsCount,
    }),
    buildQuestion({
      id: "ot-weekpart",
      question: "Is today a weekday or part of the weekend?",
      icon: "\u{1F4C6}",
      correctAnswer: isWeekend ? "Weekend" : "Weekday",
      pool: ["Weekday", "Weekend"],
      optionsCount,
    }),
    // ── Light reasoning about the calendar (uses today as the anchor) ──
    buildQuestion({
      id: "ot-tomorrow",
      question: `Today is ${weekday}. Which day comes tomorrow?`,
      icon: "➡️",
      correctAnswer: tomorrow,
      pool: WEEKDAYS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-yesterday",
      question: `Today is ${weekday}. Which day was yesterday?`,
      icon: "⬅️",
      correctAnswer: yesterday,
      pool: WEEKDAYS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-nextmonth",
      question: `It is ${month} now. Which month comes next?`,
      icon: "\u{1F5D3}️",
      correctAnswer: nextMonth,
      pool: MONTHS,
      optionsCount,
    }),
    buildNumberQuestion({
      id: "ot-daysinmonth",
      question: `How many days does ${month} have this year?`,
      icon: "\u{1F4C6}",
      answer: daysInMonth,
      pool: [28, 29, 30, 31],
      optionsCount,
    }),

    // ── Simple general-awareness facts (always true, add variety) ──
    buildNumberQuestion({
      id: "ot-days-in-week",
      question: "How many days are there in one week?",
      icon: "\u{1F5D3}️",
      answer: 7,
      pool: [5, 6, 7, 8, 10],
      optionsCount,
    }),
    buildNumberQuestion({
      id: "ot-months-in-year",
      question: "How many months are there in one year?",
      icon: "\u{1F4C5}",
      answer: 12,
      pool: [10, 11, 12, 13, 14],
      optionsCount,
    }),
    buildNumberQuestion({
      id: "ot-hours-in-day",
      question: "How many hours are there in one day?",
      icon: "⏰",
      answer: 24,
      pool: [12, 20, 24, 30, 48],
      optionsCount,
    }),
    buildQuestion({
      id: "ot-dayorder",
      question: "Which comes first in a day — morning or evening?",
      icon: "\u{1F305}",
      correctAnswer: "Morning",
      pool: ["Morning", "Evening"],
      optionsCount,
    }),
  ];

  // Shuffle so repeat players get a varied selection each round; callers take
  // the first N. The correct answer of every item is still a real fact.
  return shuffle(questions);
}

module.exports = { buildTimeOrientationQuestions, MONTHS, WEEKDAYS, TIMES_OF_DAY };
