const { shuffle, pickDistractors } = require("./gameContentUtils");

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const WEEKDAYS = [
  "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
];

const TIMES_OF_DAY = ["Morning", "Afternoon", "Evening", "Night"];

function getTimeOfDay(hour) {
  if (hour >= 5 && hour < 12) return "Morning";
  if (hour >= 12 && hour < 17) return "Afternoon";
  if (hour >= 17 && hour < 21) return "Evening";
  return "Night";
}

function buildQuestion({ id, question, icon, correctAnswer, pool, optionsCount }) {
  const options = shuffle([
    correctAnswer,
    ...pickDistractors(pool, [correctAnswer], optionsCount - 1),
  ]);
  return { id, question, icon, category: "Time", correctAnswer, options };
}

// Deterministic, real-clock orientation questions — never generated by an LLM,
// so "what year/day is it" can never be hallucinated wrong.
function buildTimeOrientationQuestions(optionsCount = 3, now = new Date()) {
  const year = now.getFullYear();
  const month = MONTHS[now.getMonth()];
  const weekday = WEEKDAYS[now.getDay()];
  const timeOfDay = getTimeOfDay(now.getHours());
  const yearPool = [year - 2, year - 1, year, year + 1, year + 2].map(String);

  return [
    buildQuestion({
      id: "ot-year",
      question: "What year is it right now?",
      icon: "\u{1F4C5}",
      correctAnswer: String(year),
      pool: yearPool,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-weekday",
      question: "What day of the week is it today?",
      icon: "\u{1F4C6}",
      correctAnswer: weekday,
      pool: WEEKDAYS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-month",
      question: "What month is it right now?",
      icon: "\u{1F5D3}️",
      correctAnswer: month,
      pool: MONTHS,
      optionsCount,
    }),
    buildQuestion({
      id: "ot-timeofday",
      question: "Is it morning, afternoon, evening, or night right now?",
      icon: "⏰",
      correctAnswer: timeOfDay,
      pool: TIMES_OF_DAY,
      optionsCount,
    }),
  ];
}

module.exports = { buildTimeOrientationQuestions, MONTHS, WEEKDAYS, TIMES_OF_DAY };
