const { shuffle, pickDistractors } = require("./gameContentUtils");

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const WEEKDAYS = [
  "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
];

const TIMES_OF_DAY = ["Morning", "Afternoon", "Evening", "Night"];

// Simple, non-distressing words used for the hard-level delayed-recall anchor:
// the patient is shown one to remember, then asked for it again at the end.
const RECALL_WORDS = [
  "Sunflower", "Elephant", "Rainbow", "Mountain", "River",
  "Garden", "Butterfly", "Lantern", "Umbrella", "Harbour",
];

function getTimeOfDay(hour) {
  if (hour >= 5 && hour < 12) return "Morning";
  if (hour >= 12 && hour < 17) return "Afternoon";
  if (hour >= 17 && hour < 21) return "Evening";
  return "Night";
}

// Neighbours of `correct` within an ordered list (e.g. Monday sits next to
// Sunday/Tuesday). Used for "near" distractors so wrong answers are genuinely
// tempting on medium/hard instead of obviously random.
function orderedNeighbours(list, correct, count) {
  const index = list.indexOf(correct);
  if (index === -1) return pickDistractors(list, [correct], count);
  const out = [];
  for (let distance = 1; out.length < count && distance < list.length; distance += 1) {
    const before = list[(index - distance + list.length) % list.length];
    const after = list[(index + distance) % list.length];
    if (before !== correct && !out.includes(before)) out.push(before);
    if (out.length >= count) break;
    if (after !== correct && !out.includes(after)) out.push(after);
  }
  return out.slice(0, count);
}

// Build a multiple-choice item. `spread` controls how close the wrong options
// sit to the correct one: "near" picks adjacent items from an ordered pool,
// "far" (the default) picks at random.
function buildChoice({ id, question, icon, category, correctAnswer, pool, optionsCount, spread, tier, hint, numeric, numericRange }) {
  const distractors =
    spread === "near"
      ? orderedNeighbours(pool, correctAnswer, optionsCount - 1)
      : pickDistractors(pool, [correctAnswer], optionsCount - 1);

  return {
    id,
    question,
    icon,
    category: category || "Time",
    correctAnswer,
    options: shuffle([correctAnswer, ...distractors]),
    tier,
    ...(hint ? { hint } : {}),
    ...(numeric ? { numeric: true } : {}),
    ...(numericRange ? { numericRange } : {}),
  };
}

// Numeric question with plausible near-miss distractors. `pool` may be a fixed
// list of candidate numbers; when omitted we generate neighbours of the answer
// (kept within [min, max]). `spread` widens ("far") or tightens ("near") the
// gap between the answer and its decoys.
function buildNumber({ id, question, icon, category, answer, pool, min = 1, max = 999, optionsCount, spread, tier, hint, range }) {
  let candidates = pool;
  if (!candidates) {
    candidates = [];
    const maxDelta = spread === "near" ? 2 : 4;
    const minDelta = spread === "near" ? 1 : 2;
    for (let delta = -maxDelta; delta <= maxDelta; delta += 1) {
      if (delta === 0 || Math.abs(delta) < minDelta) continue;
      const value = answer + delta;
      if (value >= min && value <= max) candidates.push(value);
    }
  }
  const correctAnswer = String(answer);
  const distractors = pickDistractors(candidates.map(String), [correctAnswer], optionsCount - 1);
  return {
    id,
    question,
    icon,
    category: category || "Time",
    correctAnswer,
    options: shuffle([correctAnswer, ...distractors]),
    tier,
    numeric: true,
    ...(hint ? { hint } : {}),
    ...(range ? { numericRange: range } : {}),
  };
}

// Deterministic, real-clock orientation questions — never generated by an LLM,
// so "what year/day is it" can never be hallucinated wrong. Every question is
// tagged with a cognitive `tier`:
//   1 = recognition / general knowledge (lowest load)
//   2 = current-state temporal orientation (the classic MMSE items)
//   3 = reasoning that manipulates the current date (highest load)
// `opts.tiers` selects which tiers a round may draw from and `opts.spread`
// controls distractor closeness, so each difficulty feels genuinely different.
function buildTimeOrientationQuestions(optionsCount = 3, opts = {}, now = new Date()) {
  const { tiers = [1, 2, 3], spread = "far" } = opts;

  const year = now.getFullYear();
  const monthIndex = now.getMonth();
  const month = MONTHS[monthIndex];
  const dayIndex = now.getDay();
  const weekday = WEEKDAYS[dayIndex];
  const dateOfMonth = now.getDate();
  const hour = now.getHours();
  const timeOfDay = getTimeOfDay(hour);
  // Nearby years are all tempting, so keep four either way — this also ensures
  // enough options for the higher medium/hard option counts.
  const yearPool = [year - 2, year - 1, year + 1, year + 2].map(String);
  const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();

  const tomorrow = WEEKDAYS[(dayIndex + 1) % 7];
  const yesterday = WEEKDAYS[(dayIndex + 2 + 5) % 7]; // = dayIndex - 1
  const dayAfterTomorrow = WEEKDAYS[(dayIndex + 2) % 7];
  const nextMonth = MONTHS[(monthIndex + 1) % 12];
  const twoMonthsAgo = MONTHS[(monthIndex + 10) % 12];
  const isWeekend = dayIndex === 0 || dayIndex === 6;

  const common = { optionsCount, spread };

  const questions = [
    // ── Tier 2: current date & time awareness (change with the real clock) ──
    buildChoice({
      ...common,
      id: "ot-year",
      question: "What year is it right now?",
      icon: "\u{1F4C5}",
      correctAnswer: String(year),
      pool: yearPool,
      tier: 2,
      numeric: true,
      numericRange: { min: year - 5, max: year + 5 },
      hint: "Think about the year we are living in now.",
    }),
    buildChoice({
      ...common,
      id: "ot-weekday",
      question: "What day of the week is it today?",
      icon: "\u{1F4C6}",
      correctAnswer: weekday,
      pool: WEEKDAYS,
      tier: 2,
      hint: "Think about what you did today or have planned.",
    }),
    buildChoice({
      ...common,
      id: "ot-month",
      question: "What month is it right now?",
      icon: "\u{1F5D3}️",
      correctAnswer: month,
      pool: MONTHS,
      tier: 2,
      hint: "Think about the season and any recent festivals.",
    }),
    buildChoice({
      ...common,
      id: "ot-timeofday",
      question: "Is it morning, afternoon, evening, or night right now?",
      icon: "⏰",
      correctAnswer: timeOfDay,
      pool: TIMES_OF_DAY,
      tier: 2,
      hint: "Look at how light or dark it is outside.",
    }),
    buildNumber({
      ...common,
      id: "ot-dateofmonth",
      question: "What is today's date (the day of the month)?",
      icon: "\u{1F4C5}",
      answer: dateOfMonth,
      min: 1,
      max: 31,
      tier: 2,
      range: { min: 1, max: 31 },
    }),
    buildChoice({
      ...common,
      id: "ot-ampm",
      question: "Right now, is the time AM (before noon) or PM (after noon)?",
      icon: "\u{1F55B}",
      correctAnswer: hour < 12 ? "AM" : "PM",
      pool: ["AM", "PM"],
      tier: 2,
    }),
    buildChoice({
      ...common,
      id: "ot-weekpart",
      question: "Is today a weekday or part of the weekend?",
      icon: "\u{1F4C6}",
      correctAnswer: isWeekend ? "Weekend" : "Weekday",
      pool: ["Weekday", "Weekend"],
      tier: 2,
    }),

    // ── Tier 3: light reasoning about the calendar (uses today as anchor) ──
    buildChoice({
      ...common,
      id: "ot-tomorrow",
      question: `Today is ${weekday}. Which day comes tomorrow?`,
      icon: "➡️",
      correctAnswer: tomorrow,
      pool: WEEKDAYS,
      tier: 3,
    }),
    buildChoice({
      ...common,
      id: "ot-yesterday",
      question: `Today is ${weekday}. Which day was yesterday?`,
      icon: "⬅️",
      correctAnswer: yesterday,
      pool: WEEKDAYS,
      tier: 3,
    }),
    buildChoice({
      ...common,
      id: "ot-day-after-tomorrow",
      question: `Today is ${weekday}. Which day will it be the day after tomorrow?`,
      icon: "⏩",
      correctAnswer: dayAfterTomorrow,
      pool: WEEKDAYS,
      tier: 3,
    }),
    buildChoice({
      ...common,
      id: "ot-nextmonth",
      question: `It is ${month} now. Which month comes next?`,
      icon: "\u{1F5D3}️",
      correctAnswer: nextMonth,
      pool: MONTHS,
      tier: 3,
    }),
    buildChoice({
      ...common,
      id: "ot-two-months-ago",
      question: `It is ${month} now. Which month was it two months ago?`,
      icon: "⏪",
      correctAnswer: twoMonthsAgo,
      pool: MONTHS,
      tier: 3,
    }),
    buildNumber({
      ...common,
      id: "ot-daysinmonth",
      question: `How many days does ${month} have this year?`,
      icon: "\u{1F4C6}",
      answer: daysInMonth,
      pool: [28, 29, 30, 31],
      tier: 3,
      range: { min: 28, max: 31 },
    }),

    // ── Tier 1: simple general-awareness facts (always true, lowest load) ──
    buildNumber({
      ...common,
      id: "ot-days-in-week",
      question: "How many days are there in one week?",
      icon: "\u{1F5D3}️",
      answer: 7,
      pool: [5, 6, 7, 8, 10],
      tier: 1,
    }),
    buildNumber({
      ...common,
      id: "ot-months-in-year",
      question: "How many months are there in one year?",
      icon: "\u{1F4C5}",
      answer: 12,
      pool: [10, 11, 12, 13, 14],
      tier: 1,
    }),
    buildNumber({
      ...common,
      id: "ot-hours-in-day",
      question: "How many hours are there in one day?",
      icon: "⏰",
      answer: 24,
      pool: [12, 20, 24, 30, 48],
      tier: 1,
    }),
    buildChoice({
      ...common,
      id: "ot-dayorder",
      question: "Which comes first in a day — morning or evening?",
      icon: "\u{1F305}",
      correctAnswer: "Morning",
      pool: ["Morning", "Evening"],
      tier: 1,
    }),
  ];

  const tierSet = new Set(tiers);
  const selected = questions.filter((q) => tierSet.has(q.tier));

  // Shuffle so repeat players get a varied selection each round; callers take
  // the first N. The correct answer of every item is still a real fact.
  return shuffle(selected.length ? selected : questions);
}

// A hard-level delayed-recall challenge: the patient is shown a word to hold in
// mind at the start of the round, then this question asks for it at the end.
// Deterministic and non-distressing — the answer is one of RECALL_WORDS.
function buildMemoryAnchor(optionsCount = 4) {
  const word = RECALL_WORDS[Math.floor(Math.random() * RECALL_WORDS.length)];
  const question = {
    id: "ot-recall",
    question: "Which word were you asked to remember at the start?",
    icon: "\u{1F9E0}",
    category: "Memory",
    correctAnswer: word,
    options: shuffle([word, ...pickDistractors(RECALL_WORDS, [word], optionsCount - 1)]),
    tier: 3,
  };
  const anchor = {
    word,
    icon: "\u{1F9E0}",
    statement: `Please remember this word. We will ask for it again at the end: ${word}`,
  };
  return { anchor, question };
}

module.exports = {
  buildTimeOrientationQuestions,
  buildMemoryAnchor,
  MONTHS,
  WEEKDAYS,
  TIMES_OF_DAY,
};
